# Generated by Django 5.1.7 on 2025-03-26 19:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_appointment_created_at_appointment_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=10, unique=True)),
                ('treatment_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('medicine_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], max_length=50, unique=True)),
                ('services_offered', models.TextField(blank=True, max_length=500)),
                ('doctors_list', models.ManyToManyField(related_name='departments', to='hospital.doctor')),
                ('head_of_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of', to='hospital.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=15, unique=True)),
                ('diagnosis', models.TextField(max_length=500)),
                ('prescribed_treatment', models.TextField(blank=True, max_length=500)),
                ('test_results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_id', models.CharField(max_length=10, unique=True)),
                ('available_medicines', models.JSONField(default=dict)),
                ('pharmacist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescriptions_list', models.ManyToManyField(blank=True, to='hospital.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='WardRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(choices=[('ICU', 'ICU'), ('General', 'General'), ('Private', 'Private')], max_length=20)),
                ('availability', models.BooleanField(default=True)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('assigned_patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.patient')),
            ],
        ),
    ]
