# Generated by Django 5.1.7 on 2025-04-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_patient_age_patient_email_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic/PatientProfilePic/'),
        ),
    ]
