# Generated by Django 5.2 on 2025-05-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_alter_pharmacy_pharmacist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='available_medicines',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
