# Generated by Django 5.2 on 2025-05-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_alter_pharmacy_available_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_quantities',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
