# Generated by Django 5.2 on 2025-05-12 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_medicalrecord_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='medical_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.medicalrecord'),
        ),
    ]
