# Generated by Django 5.2 on 2025-05-12 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_billing_medical_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardroom',
            name='assigned_patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ward', to='hospital.patient'),
        ),
    ]
