# Generated by Django 5.2 on 2025-05-12 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0029_alter_wardroom_assigned_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='dispensed_items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wardroom',
            name='assigned_patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_room', to='hospital.patient'),
        ),
    ]
