# Generated by Django 5.2 on 2025-05-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_medicalrecord_dispensed_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='prescribed_treatment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment_quantities',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
