# Generated by Django 5.2 on 2025-05-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0031_alter_medicalrecord_prescribed_treatment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='address',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='hireDate',
        ),
        migrations.AlterField(
            model_name='nurse',
            name='assignedWard',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
